name: CI
on: [push, pull_request]
jobs:
  cross-validate:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          device-family: [spartan6, spartan3a_dsp]
    steps:
      - name: check out repository code
        uses: actions/checkout@v2
      - name: setup environment & run cross validation
        run:  |
          source setup_env.sh
          python3 scripts/test.py testing_inputs/samples.dat --device_family ${{ matrix.device-family }}
